import {
  ArtIcon,
  BeautyIcon,
  DailyIcon,
  EntertainmentIcon,
  FashionIcon,
  FoodIcon,
  GameIcon,
  LiteratureIcon,
  MovieIcon,
  MusicIcon,
  PetsIcon,
  PhotographyIcon,
  SportsIcon,
  TechIcon,
  TravelIcon,
} from '@/assets/assets';

export const INTEREST_TAGS = [
  { id: 1, label: 'Music', icon: MusicIcon },
  { id: 2, label: 'Pets', icon: PetsIcon },
  { id: 3, label: 'Daily', icon: DailyIcon },
  { id: 4, label: 'Tech', icon: TechIcon },
  { id: 5, label: 'Travel', icon: TravelIcon },
  { id: 6, label: 'Food', icon: FoodIcon },
  { id: 7, label: 'Literature', icon: LiteratureIcon },
  { id: 8, label: 'Entertainment', icon: EntertainmentIcon },
  { id: 9, label: 'Art', icon: ArtIcon },
  { id: 10, label: 'Fashion', icon: FashionIcon },
  { id: 11, label: 'Movie', icon: MovieIcon },
  { id: 12, label: 'Beauty', icon: BeautyIcon },
  { id: 13, label: 'Games', icon: GameIcon },
  { id: 14, label: 'Photography', icon: PhotographyIcon },
  { id: 15, label: 'Sports', icon: SportsIcon },
];
