export enum NotificationType {
  FOLLOW = 'FOLLOW',
  COMMENT = 'COMMENT',
  RECOMMENT = 'RECOMMENT',
  CHAT = 'CHAT',
  VOICEREPLY = 'VOICEREPLY',
  BOARDLIKE = 'BOARDLIKE',
  COMMENTLIKE = 'COMMENTLIKE',
  REPLYLIKE = 'REPLYLIKE',
}
