// 회원가입 단계별 메세지
export const steps = [
  {
    message1: 'Hi! It’s your first time here, huh?',
    message2: 'What’s your name? 😎',
    message3: '',
    placeholder: 'Enter your name',
    rule: '영어 최대 8글자, 특수기호 불가',
    inputType: 'text',
  },
  {
    message1: 'Oh, my bad! I meant to ask',
    message2: 'what ID you wanna go with😅',
    message3: '',
    placeholder: 'Enter your ID',
    rule: '영어 4~14자, 대,소문자/숫자/_/. 사용 가능',
    inputType: 'text',
  },
  {
    message1: 'Alright, now',
    message2: 'let’s pick a password! 🔒✨',
    message3: '',
    placeholder: 'Enter your password',
    rule: '영어 4~16자, 대,소문자/숫자 사용 가능',
    inputType: 'text',
  },
  {
    message1: 'Wait, what was the password',
    message2: 'you just said again? 🤔💬',
    message3: '',
    placeholder: 'Enter your password again',
    rule: '',
    inputType: 'text',
  },
  {
    message1: 'Drop your email too 📧✨',
    message2: '',
    message3: '',
    placeholder: 'Enter your email',
    rule: '',
    inputType: 'email',
  },
  // {
  //   message1: 'Yeah, that’s it, for sure! 😎',
  //   message2: 'Do you have a pic of yourself? 🤔📷',
  //   message3: '',
  //   placeholder: '',
  //   rule: '',
  //   inputType: 'choice',
  // },
  {
    message1: 'Oh, then drop your',
    message2: 'most slay pic! 😎📸',
    message3: '',
    placeholder: '',
    rule: '',
    inputType: 'file',
  },
  {
    message1: "We're almost done signing up!",
    message2: 'When’s your b-day? 🎂',
    message3: '',
    placeholder: '',
    rule: '',
    inputType: 'date',
  },
  {
    message1: 'So, like, what kinda vibe',
    message2: 'are you giving off? 🤔✨',
    message3: '',
    placeholder: 'Introduce yourself',
    rule: '',
    inputType: 'textarea',
  },
  {
    message1: 'Alright, last thing—  ',
    message2: 'what’s your fave stuff? 🧐✨',
    message3: '',
    placeholder: '',
    rule: '',
    inputType: 'tags',
  },
  {
    message1: 'Thanks for the info!',
    message2: 'Yo, you’re like, our new bestie now.',
    message3: 'Catch ya later, fam! 😎✌️',
    placeholder: '',
    rule: '',
    inputType: '',
  },
];
